# nginx/nginx.conf
worker_processes auto;

events {}

http {
    # Rate limiting
    limit_req_zone $binary_remote_addr zone=limit:10m rate=10r/s;

    # Basic auth
    auth_basic "Restricted";
    auth_basic_user_file /etc/nginx/.htpasswd;

    # Upstreams
    upstream api_v1_cluster {
        server api_v1:8000;
        server api_v1:8000;
        server api_v1:8000;
    }

    upstream api_v2_cluster {
        server api_v2:8000;
    }

    # Redirect HTTP → HTTPS
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    # HTTPS server
    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/nginx.crt;
        ssl_certificate_key /etc/nginx/nginx.key;

        location /predict {
            limit_req zone=limit;

            # A/B testing
            if ($http_x_experiment_group = "debug") {
                proxy_pass http://api_v2_cluster;
            }

            proxy_pass http://api_v1_cluster;
        }
    }
}
